# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='Phone Number'),
        ),
    ]
