# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-22 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170120_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
